### ISSUE TITLE
visqol installation

### ISSUE THREAD

**Issue by 198thread** [JusperLee/Apollo#3]
I'm trying to make a platform agnostic install (a environment.yml + poetry)

I've noticed the package visqol is not found in conda or pip repos. This package requires [building](https://github.com/google/visqol?tab=readme-ov-file#build).

Can anyone else confirm that this?

It breaks the current installation instructions for me. 

Host: Win64

**Comment by ivcylc** [comment]
installing of VISQOL is quite difficult...

**Comment by JusperLee** [comment]
If you don't want to test visqol, you can delete this part in the req.txt.
